
code_names = ['General',
              'Another party',
              'Specific person',
              'Ideology',
              'Electability',
              'Scandal',
              'Campaign',
              'Other past activity',
              'Ability',
              'Honesty',
              'Intelligence',
              'Leadership',
              'Management',
              'Religion',
              'Education',
              'Physical appearance',
              'Demographics',
              'Policy-Economic',
              'Policy-Poor people',
              'Policy-Liberty',
              'Policy-Enemy countries',
              'Policy-Friendly countries',
              'Policy-General foreign',
              'Policy-Other',
              'Groups',
              'Emotions/Feelings',
              'Party-Other',
              'Non-party',
              'Party membership',
              "Don't know",
              'Refuse to answer',
              'Respondent-Other',
              'Other']